CREATE TABLE workout_database.USER(
    USER_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NAME TEXT NOT NULL,
    EMAIL TEXT NOT NULL
);

CREATE TABLE workout_database.TRAINING_DETAILS(
    TRAINING_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DATE TEXT NOT NULL,
    USER_ID BIGINT(20),
    CONSTRAINT FK_USER_ID FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)
);
