CREATE TABLE workout_database.EXERCISES (
    EXERCISE_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    EXERCISE_NAME TEXT NOT NULL,
    BODY_PART TEXT NOT NULL
);

CREATE TABLE workout_database.EXERCISE_ON_TRAINING(
  TRAINING_ID BIGINT(20) NOT NULL,
  EXERCISE_ID BIGINT(20) NOT NULL,
  CONSTRAINT FK_TRAINING_ID FOREIGN KEY (TRAINING_ID) REFERENCES TRAINING_DETAILS(TRAINING_ID),
  CONSTRAINT FK_EXERCISE_ID FOREIGN KEY (EXERCISE_ID) REFERENCES EXERCISES(EXERCISE_ID)
);

