ALTER TABLE workout_database.EXERCISE_ON_TRAINING
    ADD COLUMN EXERCISE_ON_TRAINING_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT;

ALTER TABLE workout_database.EXERCISE_ON_TRAINING
    ADD COLUMN SERIES_NUMBER BIGINT(10);

ALTER TABLE workout_database.EXERCISE_ON_TRAINING
    ADD COLUMN REPETITIONS BIGINT(10);

ALTER TABLE workout_database.EXERCISE_ON_TRAINING
    ADD COLUMN WEIGHT BIGINT(10);
